# This is a basic workflow to help you get started with Actions

name: Build Broadcom

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: parepare
        run: |
          sudo apt install -y python3-pip
          sudo pip3 install j2cli
      - name: make init
        run: make init
      - name: make configure
        run: make configure PLATFORM=broadcom
      - name: build debian buster required targets
        run: BLDENV=buster make buster
      - name: build ONIE image
        run: make target/sonic-broadcom.bin
      - name: build EOS image
        run: make target/sonic-aboot-broadcom.swi
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: target-${{ github.run_id }}
          path: target/*
